export const MOCK_FETCH_CATS_REPSONSE = {
  cats: [
    {
      breeds: [],
      id: '1i5',
      url: 'https://cdn2.thecatapi.com/images/1i5.jpg',
      width: 500,
      height: 375,
    },
    {
      breeds: [],
      id: '2gn',
      url: 'https://cdn2.thecatapi.com/images/2gn.jpg',
      width: 500,
      height: 333,
    },
    {
      breeds: [],
      categories: [
        {
          id: 9,
          name: 'dream',
        },
      ],
      id: '31p',
      url: 'https://cdn2.thecatapi.com/images/31p.jpg',
      width: 640,
      height: 458,
    },
    {
      breeds: [],
      categories: [
        {
          id: 2,
          name: 'space',
        },
      ],
      id: '5ge',
      url: 'https://cdn2.thecatapi.com/images/5ge.jpg',
      width: 633,
      height: 500,
    },
    {
      breeds: [],
      categories: [
        {
          id: 2,
          name: 'space',
        },
      ],
      id: '5h0',
      url: 'https://cdn2.thecatapi.com/images/5h0.jpg',
      width: 693,
      height: 500,
    },
    {
      breeds: [],
      id: 'al7',
      url: 'https://cdn2.thecatapi.com/images/al7.jpg',
      width: 500,
      height: 690,
    },
    {
      breeds: [],
      id: 'b4t',
      url: 'https://cdn2.thecatapi.com/images/b4t.jpg',
      width: 3753,
      height: 4915,
    },
    {
      breeds: [],
      id: 'b7j',
      url: 'https://cdn2.thecatapi.com/images/b7j.jpg',
      width: 500,
      height: 374,
    },
    {
      breeds: [],
      id: 'd23',
      url: 'https://cdn2.thecatapi.com/images/d23.gif',
      width: 500,
      height: 375,
    },
    {
      breeds: [
        {
          weight: {
            imperial: '7 - 12',
            metric: '3 - 5',
          },
          id: 'snow',
          name: 'Snowshoe',
          temperament: 'Affectionate, Social, Intelligent, Sweet-tempered',
          origin: 'United States',
          country_codes: 'US',
          country_code: 'US',
          description:
            'The Snowshoe is a vibrant, energetic, affectionate and intelligent cat. They love being around people which makes them ideal for families, and becomes unhappy when left alone for long periods of time. Usually attaching themselves to one person, they do whatever they can to get your attention.',
          life_span: '14 - 19',
          indoor: 0,
          lap: 1,
          alt_names: '',
          adaptability: 5,
          affection_level: 5,
          child_friendly: 4,
          dog_friendly: 5,
          energy_level: 4,
          grooming: 3,
          health_issues: 1,
          intelligence: 5,
          shedding_level: 3,
          social_needs: 4,
          stranger_friendly: 4,
          vocalisation: 5,
          experimental: 0,
          hairless: 0,
          natural: 0,
          rare: 0,
          rex: 0,
          suppressed_tail: 0,
          short_legs: 0,
          wikipedia_url: 'https://en.wikipedia.org/wiki/Snowshoe_(cat)',
          hypoallergenic: 0,
          reference_image_id: 'MK-sYESvO',
        },
      ],
      id: '_qUK20W2d',
      url: 'https://cdn2.thecatapi.com/images/_qUK20W2d.jpg',
      width: 1080,
      height: 1080,
    },
  ],
  paginationCount: 8085,
};
