export const MOCK_FETCH_CATS_REPSONSE = {
  cats: [
    {
      breeds: [
        {
          weight: {
            imperial: '4 - 10',
            metric: '2 - 5',
          },
          id: 'bali',
          name: 'Balinese',
          cfa_url: 'http://cfa.org/Breeds/BreedsAB/Balinese.aspx',
          vetstreet_url: 'http://www.vetstreet.com/cats/balinese',
          vcahospitals_url:
            'https://vcahospitals.com/know-your-pet/cat-breeds/balinese',
          temperament: 'Affectionate, Intelligent, Playful',
          origin: 'United States',
          country_codes: 'US',
          country_code: 'US',
          description:
            'Balinese are curious, outgoing, intelligent cats with excellent communication skills. They are known for their chatty personalities and are always eager to tell you their views on life, love, and what you’ve served them for dinner. ',
          life_span: '10 - 15',
          indoor: 0,
          alt_names: 'Long-haired Siamese',
          adaptability: 5,
          affection_level: 5,
          child_friendly: 4,
          dog_friendly: 5,
          energy_level: 5,
          grooming: 3,
          health_issues: 3,
          intelligence: 5,
          shedding_level: 3,
          social_needs: 5,
          stranger_friendly: 5,
          vocalisation: 5,
          experimental: 0,
          hairless: 0,
          natural: 0,
          rare: 0,
          rex: 0,
          suppressed_tail: 0,
          short_legs: 0,
          wikipedia_url: 'https://en.wikipedia.org/wiki/Balinese_(cat)',
          hypoallergenic: 1,
          reference_image_id: '13MkvUreZ',
        },
      ],
      id: 'SwjDQ76Ix',
      url: 'https://cdn2.thecatapi.com/images/SwjDQ76Ix.jpg',
      width: 1620,
      height: 1080,
    },
    {
      breeds: [
        {
          weight: {
            imperial: '5 - 9',
            metric: '2 - 4',
          },
          id: 'crex',
          name: 'Cornish Rex',
          cfa_url: 'http://cfa.org/Breeds/BreedsCJ/CornishRex.aspx',
          vetstreet_url: 'http://www.vetstreet.com/cats/cornish-rex',
          vcahospitals_url:
            'https://vcahospitals.com/know-your-pet/cat-breeds/cornish-rex',
          temperament: 'Affectionate, Intelligent, Active, Curious, Playful',
          origin: 'United Kingdom',
          country_codes: 'GB',
          country_code: 'GB',
          description:
            'This is a confident cat who loves people and will follow them around, waiting for any opportunity to sit in a lap or give a kiss. He enjoys being handled, making it easy to take him to the veterinarian or train him for therapy work. The Cornish Rex stay in kitten mode most of their lives and well into their senior years. ',
          life_span: '11 - 14',
          indoor: 0,
          lap: 1,
          alt_names: '',
          adaptability: 5,
          affection_level: 5,
          child_friendly: 4,
          cat_friendly: 2,
          dog_friendly: 5,
          energy_level: 5,
          grooming: 1,
          health_issues: 2,
          intelligence: 5,
          shedding_level: 1,
          social_needs: 5,
          stranger_friendly: 3,
          vocalisation: 1,
          experimental: 0,
          hairless: 0,
          natural: 0,
          rare: 0,
          rex: 1,
          suppressed_tail: 0,
          short_legs: 0,
          wikipedia_url: 'https://en.wikipedia.org/wiki/Cornish_Rex',
          hypoallergenic: 1,
          reference_image_id: 'unX21IBVB',
        },
      ],
      id: 'RIRLq-8sp',
      url: 'https://cdn2.thecatapi.com/images/RIRLq-8sp.jpg',
      width: 1250,
      height: 702,
    },
    {
      breeds: [
        {
          weight: {
            imperial: '4 - 10',
            metric: '2 - 5',
          },
          id: 'csho',
          name: 'Colorpoint Shorthair',
          cfa_url: 'http://cfa.org/Breeds/BreedsCJ/ColorpointShorthair.aspx',
          vcahospitals_url:
            'https://vcahospitals.com/know-your-pet/cat-breeds/colorpoint-shorthair',
          temperament: 'Affectionate, Intelligent, Playful, Social',
          origin: 'United States',
          country_codes: 'US',
          country_code: 'US',
          description:
            'Colorpoint Shorthairs are an affectionate breed, devoted and loyal to their people. Sensitive to their owner’s moods, Colorpoints are more than happy to sit at your side or on your lap and purr words of encouragement on a bad day. They will constantly seek out your lap whenever it is open and in the moments when your lap is preoccupied they will stretch out in sunny spots on the ground.',
          life_span: '12 - 16',
          indoor: 0,
          lap: 1,
          alt_names: '',
          adaptability: 3,
          affection_level: 4,
          child_friendly: 4,
          cat_friendly: 3,
          dog_friendly: 4,
          energy_level: 4,
          grooming: 2,
          health_issues: 2,
          intelligence: 5,
          shedding_level: 3,
          social_needs: 4,
          stranger_friendly: 2,
          vocalisation: 5,
          bidability: 4,
          experimental: 0,
          hairless: 0,
          natural: 0,
          rare: 0,
          rex: 0,
          suppressed_tail: 0,
          short_legs: 0,
          wikipedia_url: 'https://en.wikipedia.org/wiki/Colorpoint_Shorthair',
          hypoallergenic: 0,
          reference_image_id: 'oSpqGyUDS',
        },
      ],
      id: 'oSpqGyUDS',
      url: 'https://cdn2.thecatapi.com/images/oSpqGyUDS.jpg',
      width: 1363,
      height: 1600,
    },
    {
      breeds: [
        {
          weight: {
            imperial: '6 - 10',
            metric: '3 - 5',
          },
          id: 'lape',
          name: 'LaPerm',
          cfa_url: 'http://cfa.org/Breeds/BreedsKthruR/LaPerm.aspx',
          vetstreet_url: 'http://www.vetstreet.com/cats/laperm',
          vcahospitals_url:
            'https://vcahospitals.com/know-your-pet/cat-breeds/laperm',
          temperament:
            'Affectionate, Friendly, Gentle, Intelligent, Playful, Quiet',
          origin: 'Thailand',
          country_codes: 'TH',
          country_code: 'TH',
          description:
            'LaPerms are gentle and affectionate but also very active. Unlike many active breeds, the LaPerm is also quite content to be a lap cat. The LaPerm will often follow your lead; that is, if they are busy playing and you decide to sit and relax, simply pick up your LaPerm and sit down with it, and it will stay in your lap, devouring the attention you give it.',
          life_span: '10 - 15',
          indoor: 0,
          lap: 1,
          alt_names: 'Si-Sawat',
          adaptability: 5,
          affection_level: 5,
          child_friendly: 4,
          dog_friendly: 5,
          energy_level: 4,
          grooming: 1,
          health_issues: 1,
          intelligence: 5,
          shedding_level: 3,
          social_needs: 4,
          stranger_friendly: 4,
          vocalisation: 3,
          experimental: 0,
          hairless: 0,
          natural: 0,
          rare: 0,
          rex: 1,
          suppressed_tail: 0,
          short_legs: 0,
          wikipedia_url: 'https://en.wikipedia.org/wiki/LaPerm',
          hypoallergenic: 1,
          reference_image_id: 'aKbsEYjSl',
        },
      ],
      id: 'ggoVRMisX',
      url: 'https://cdn2.thecatapi.com/images/ggoVRMisX.jpg',
      width: 1600,
      height: 848,
    },
    {
      breeds: [
        {
          weight: {
            imperial: '5 - 9',
            metric: '2 - 4',
          },
          id: 'munc',
          name: 'Munchkin',
          vetstreet_url: 'http://www.vetstreet.com/cats/munchkin',
          temperament: 'Agile, Easy Going, Intelligent, Playful',
          origin: 'United States',
          country_codes: 'US',
          country_code: 'US',
          description:
            'The Munchkin is an outgoing cat who enjoys being handled. She has lots of energy and is faster and more agile than she looks. The shortness of their legs does not seem to interfere with their running and leaping abilities.',
          life_span: '10 - 15',
          indoor: 0,
          lap: 1,
          alt_names: '',
          adaptability: 5,
          affection_level: 5,
          child_friendly: 4,
          dog_friendly: 5,
          energy_level: 4,
          grooming: 2,
          health_issues: 3,
          intelligence: 5,
          shedding_level: 3,
          social_needs: 5,
          stranger_friendly: 5,
          vocalisation: 3,
          experimental: 0,
          hairless: 0,
          natural: 0,
          rare: 0,
          rex: 0,
          suppressed_tail: 0,
          short_legs: 1,
          wikipedia_url: 'https://en.wikipedia.org/wiki/Munchkin_(cat)',
          hypoallergenic: 0,
          reference_image_id: 'j5cVSqLer',
        },
      ],
      id: 'gVzbbInLF',
      url: 'https://cdn2.thecatapi.com/images/gVzbbInLF.jpg',
      width: 1000,
      height: 664,
    },
    {
      breeds: [
        {
          weight: {
            imperial: '7 - 15',
            metric: '3 - 7',
          },
          id: 'ocic',
          name: 'Ocicat',
          cfa_url: 'http://cfa.org/Breeds/BreedsKthruR/Ocicat.aspx',
          vetstreet_url: 'http://www.vetstreet.com/cats/ocicat',
          vcahospitals_url:
            'https://vcahospitals.com/know-your-pet/cat-breeds/ocicat',
          temperament:
            'Active, Agile, Curious, Demanding, Friendly, Gentle, Lively, Playful, Social',
          origin: 'United States',
          country_codes: 'US',
          country_code: 'US',
          description:
            "Loyal and devoted to their owners, the Ocicat is intelligent, confident, outgoing, and seems to have many dog traits. They can be trained to fetch toys, walk on a lead, taught to 'speak', come when called, and follow other commands. ",
          life_span: '12 - 14',
          indoor: 0,
          alt_names: '',
          adaptability: 5,
          affection_level: 5,
          child_friendly: 4,
          dog_friendly: 5,
          energy_level: 5,
          grooming: 1,
          health_issues: 3,
          intelligence: 5,
          shedding_level: 3,
          social_needs: 5,
          stranger_friendly: 5,
          vocalisation: 3,
          experimental: 0,
          hairless: 0,
          natural: 0,
          rare: 0,
          rex: 0,
          suppressed_tail: 0,
          short_legs: 0,
          wikipedia_url: 'https://en.wikipedia.org/wiki/Ocicat',
          hypoallergenic: 1,
          reference_image_id: 'JAx-08Y0n',
        },
      ],
      id: 'TboUiIDUO',
      url: 'https://cdn2.thecatapi.com/images/TboUiIDUO.jpg',
      width: 1200,
      height: 804,
    },
    {
      breeds: [
        {
          weight: {
            imperial: '8 - 17',
            metric: '4 - 8',
          },
          id: 'pixi',
          name: 'Pixie-bob',
          vetstreet_url: 'http://www.vetstreet.com/cats/pixiebob',
          temperament: 'Affectionate, Social, Intelligent, Loyal',
          origin: 'United States',
          country_codes: 'US',
          country_code: 'US',
          description:
            'Companionable and affectionate, the Pixie-bob wants to be an integral part of the family. The Pixie-Bob’s ability to bond with their humans along with their patient personas make them excellent companions for children.',
          life_span: '13 - 16',
          indoor: 0,
          lap: 1,
          alt_names: '',
          adaptability: 5,
          affection_level: 5,
          child_friendly: 4,
          dog_friendly: 5,
          energy_level: 4,
          grooming: 1,
          health_issues: 2,
          intelligence: 5,
          shedding_level: 3,
          social_needs: 4,
          stranger_friendly: 4,
          vocalisation: 1,
          experimental: 0,
          hairless: 0,
          natural: 0,
          rare: 0,
          rex: 0,
          suppressed_tail: 1,
          short_legs: 0,
          wikipedia_url: 'https://en.wikipedia.org/wiki/Pixiebob',
          hypoallergenic: 0,
          reference_image_id: 'z7fJRNeN6',
        },
      ],
      id: 'z7fJRNeN6',
      url: 'https://cdn2.thecatapi.com/images/z7fJRNeN6.jpg',
      width: 1024,
      height: 683,
    },
    {
      breeds: [
        {
          weight: {
            imperial: '5 - 11',
            metric: '2 - 5',
          },
          id: 'sfol',
          name: 'Scottish Fold',
          cfa_url: 'http://cfa.org/Breeds/BreedsSthruT/ScottishFold.aspx',
          vetstreet_url:
            'http://www.vetstreet.com/cats/scottish-fold-highland-fold',
          vcahospitals_url:
            'https://vcahospitals.com/know-your-pet/cat-breeds/scottish-fold',
          temperament:
            'Affectionate, Intelligent, Loyal, Playful, Social, Sweet, Loving',
          origin: 'United Kingdom',
          country_codes: 'GB',
          country_code: 'GB',
          description:
            'The Scottish Fold is a sweet, charming breed. She is an easy cat to live with and to care for. She is affectionate and is comfortable with all members of her family. Her tail should be handled gently. Folds are known for sleeping on their backs, and for sitting with their legs stretched out and their paws on their belly. This is called the "Buddha Position".',
          life_span: '11 - 14',
          indoor: 0,
          alt_names: 'Scot Fold',
          adaptability: 5,
          affection_level: 5,
          child_friendly: 4,
          dog_friendly: 5,
          energy_level: 3,
          grooming: 1,
          health_issues: 4,
          intelligence: 3,
          shedding_level: 3,
          social_needs: 3,
          stranger_friendly: 3,
          vocalisation: 1,
          experimental: 0,
          hairless: 0,
          natural: 0,
          rare: 0,
          rex: 0,
          suppressed_tail: 0,
          short_legs: 0,
          wikipedia_url: 'https://en.wikipedia.org/wiki/Scottish_Fold',
          hypoallergenic: 0,
          reference_image_id: 'o9t0LDcsa',
        },
      ],
      id: 'JQMGbOP3q',
      url: 'https://cdn2.thecatapi.com/images/JQMGbOP3q.jpg',
      width: 1365,
      height: 2048,
    },
    {
      breeds: [
        {
          weight: {
            imperial: '8 - 16',
            metric: '4 - 7',
          },
          id: 'sibe',
          name: 'Siberian',
          cfa_url: 'http://cfa.org/Breeds/BreedsSthruT/Siberian.aspx',
          vetstreet_url: 'http://www.vetstreet.com/cats/siberian',
          vcahospitals_url:
            'https://vcahospitals.com/know-your-pet/cat-breeds/siberian',
          temperament:
            'Curious, Intelligent, Loyal, Sweet, Agile, Playful, Affectionate',
          origin: 'Russia',
          country_codes: 'RU',
          country_code: 'RU',
          description:
            'The Siberians dog like temperament and affection makes the ideal lap cat and will live quite happily indoors. Very agile and powerful, the Siberian cat can easily leap and reach high places, including the tops of refrigerators and even doors. ',
          life_span: '12 - 15',
          indoor: 0,
          lap: 1,
          alt_names: 'Moscow Semi-longhair, HairSiberian Forest Cat',
          adaptability: 5,
          affection_level: 5,
          child_friendly: 4,
          dog_friendly: 5,
          energy_level: 5,
          grooming: 2,
          health_issues: 2,
          intelligence: 5,
          shedding_level: 3,
          social_needs: 4,
          stranger_friendly: 3,
          vocalisation: 1,
          experimental: 0,
          hairless: 0,
          natural: 1,
          rare: 0,
          rex: 0,
          suppressed_tail: 0,
          short_legs: 0,
          wikipedia_url: 'https://en.wikipedia.org/wiki/Siberian_(cat)',
          hypoallergenic: 1,
          reference_image_id: '3bkZAjRh1',
        },
      ],
      id: 'HNNrk-UxN',
      url: 'https://cdn2.thecatapi.com/images/HNNrk-UxN.jpg',
      width: 1080,
      height: 1080,
    },
    {
      breeds: [
        {
          weight: {
            imperial: '5 - 8',
            metric: '2 - 4',
          },
          id: 'sing',
          name: 'Singapura',
          cfa_url: 'http://cfa.org/Breeds/BreedsSthruT/Singapura.aspx',
          vetstreet_url: 'http://www.vetstreet.com/cats/singapura',
          vcahospitals_url:
            'https://vcahospitals.com/know-your-pet/cat-breeds/singapura',
          temperament:
            'Affectionate, Curious, Easy Going, Intelligent, Interactive, Lively, Loyal',
          origin: 'Singapore',
          country_codes: 'SP',
          country_code: 'SP',
          description:
            'The Singapura is usually cautious when it comes to meeting new people, but loves attention from his family so much that she sometimes has the reputation of being a pest. This is a highly active, curious and affectionate cat. She may be small, but she knows she’s in charge',
          life_span: '12 - 15',
          indoor: 0,
          lap: 1,
          alt_names: 'Drain Cat, Kucinta, Pura',
          adaptability: 5,
          affection_level: 5,
          child_friendly: 4,
          dog_friendly: 5,
          energy_level: 5,
          grooming: 1,
          health_issues: 1,
          intelligence: 5,
          shedding_level: 3,
          social_needs: 5,
          stranger_friendly: 5,
          vocalisation: 1,
          experimental: 0,
          hairless: 0,
          natural: 0,
          rare: 0,
          rex: 0,
          suppressed_tail: 0,
          short_legs: 0,
          wikipedia_url: 'https://en.wikipedia.org/wiki/Singapura_(cat)',
          hypoallergenic: 0,
          reference_image_id: 'Qtncp2nRe',
        },
      ],
      id: 'VGzO6r82_',
      url: 'https://cdn2.thecatapi.com/images/VGzO6r82_.jpg',
      width: 1600,
      height: 1200,
    },
    {
      breeds: [
        {
          weight: {
            imperial: '8 - 16',
            metric: '4 - 7',
          },
          id: 'cypr',
          name: 'Cyprus',
          temperament: 'Affectionate, Social',
          origin: 'Cyprus',
          country_codes: 'CY',
          country_code: 'CY',
          description:
            'Loving, loyal, social and inquisitive, the Cyprus cat forms strong ties with their families and love nothing more than to be involved in everything that goes on in their surroundings. They are not overly active by nature which makes them the perfect companion for people who would like to share their homes with a laid-back relaxed feline companion. ',
          life_span: '12 - 15',
          indoor: 0,
          lap: 1,
          alt_names: 'Cypriot cat',
          adaptability: 5,
          affection_level: 5,
          child_friendly: 4,
          dog_friendly: 5,
          energy_level: 4,
          grooming: 3,
          health_issues: 1,
          intelligence: 3,
          shedding_level: 3,
          social_needs: 3,
          stranger_friendly: 4,
          vocalisation: 3,
          experimental: 0,
          hairless: 0,
          natural: 1,
          rare: 0,
          rex: 0,
          suppressed_tail: 0,
          short_legs: 0,
          wikipedia_url: 'https://en.wikipedia.org/wiki/Cyprus_cat',
          hypoallergenic: 0,
          reference_image_id: 'tJbzb7FKo',
        },
      ],
      id: 'tJbzb7FKo',
      url: 'https://cdn2.thecatapi.com/images/tJbzb7FKo.jpg',
      width: 1024,
      height: 768,
    },
    {
      breeds: [
        {
          weight: {
            imperial: '8 - 16',
            metric: '4 - 7',
          },
          id: 'cypr',
          name: 'Cyprus',
          temperament: 'Affectionate, Social',
          origin: 'Cyprus',
          country_codes: 'CY',
          country_code: 'CY',
          description:
            'Loving, loyal, social and inquisitive, the Cyprus cat forms strong ties with their families and love nothing more than to be involved in everything that goes on in their surroundings. They are not overly active by nature which makes them the perfect companion for people who would like to share their homes with a laid-back relaxed feline companion. ',
          life_span: '12 - 15',
          indoor: 0,
          lap: 1,
          alt_names: 'Cypriot cat',
          adaptability: 5,
          affection_level: 5,
          child_friendly: 4,
          dog_friendly: 5,
          energy_level: 4,
          grooming: 3,
          health_issues: 1,
          intelligence: 3,
          shedding_level: 3,
          social_needs: 3,
          stranger_friendly: 4,
          vocalisation: 3,
          experimental: 0,
          hairless: 0,
          natural: 1,
          rare: 0,
          rex: 0,
          suppressed_tail: 0,
          short_legs: 0,
          wikipedia_url: 'https://en.wikipedia.org/wiki/Cyprus_cat',
          hypoallergenic: 0,
          reference_image_id: 'tJbzb7FKo',
        },
      ],
      id: 'cruhNBsv1',
      url: 'https://cdn2.thecatapi.com/images/cruhNBsv1.jpg',
      width: 1024,
      height: 768,
    },
    {
      breeds: [
        {
          weight: {
            imperial: '12 - 18',
            metric: '5 - 8',
          },
          id: 'mcoo',
          name: 'Maine Coon',
          cfa_url: 'http://cfa.org/Breeds/BreedsKthruR/MaineCoon.aspx',
          vetstreet_url: 'http://www.vetstreet.com/cats/maine-coon',
          vcahospitals_url:
            'https://vcahospitals.com/know-your-pet/cat-breeds/maine-coon',
          temperament: 'Adaptable, Intelligent, Loving, Gentle, Independent',
          origin: 'United States',
          country_codes: 'US',
          country_code: 'US',
          description:
            'They are known for their size and luxurious long coat Maine Coons are considered a gentle giant. The good-natured and affable Maine Coon adapts well to many lifestyles and personalities. She likes being with people and has the habit of following them around, but isn’t needy. Most Maine Coons love water and they can be quite good swimmers.',
          life_span: '12 - 15',
          indoor: 0,
          lap: 1,
          alt_names:
            'Coon Cat, Maine Cat, Maine Shag, Snowshoe Cat, American Longhair, The Gentle Giants',
          adaptability: 5,
          affection_level: 5,
          child_friendly: 4,
          dog_friendly: 5,
          energy_level: 3,
          grooming: 3,
          health_issues: 3,
          intelligence: 5,
          shedding_level: 3,
          social_needs: 3,
          stranger_friendly: 5,
          vocalisation: 1,
          experimental: 0,
          hairless: 0,
          natural: 1,
          rare: 0,
          rex: 0,
          suppressed_tail: 0,
          short_legs: 0,
          wikipedia_url: 'https://en.wikipedia.org/wiki/Maine_Coon',
          hypoallergenic: 0,
          reference_image_id: 'OOD3VXAQn',
        },
      ],
      id: '6JCuKEGDQ',
      url: 'https://cdn2.thecatapi.com/images/6JCuKEGDQ.jpg',
      width: 680,
      height: 1020,
    },
    {
      breeds: [
        {
          weight: {
            imperial: '6 - 16',
            metric: '3 - 7',
          },
          id: 'srex',
          name: 'Selkirk Rex',
          cfa_url: 'http://cfa.org/Breeds/BreedsSthruT/SelkirkRex.aspx',
          vetstreet_url: 'http://www.vetstreet.com/cats/selkirk-rex',
          vcahospitals_url:
            'https://vcahospitals.com/know-your-pet/cat-breeds/selkirk-rex',
          temperament:
            'Active, Affectionate, Dependent, Gentle, Patient, Playful, Quiet, Social',
          origin: 'United States',
          country_codes: 'US',
          country_code: 'US',
          description:
            'The Selkirk Rex is an incredibly patient, loving, and tolerant breed. The Selkirk also has a silly side and is sometimes described as clownish. She loves being a lap cat and will be happy to chat with you in a quiet voice if you talk to her. ',
          life_span: '14 - 15',
          indoor: 0,
          lap: 1,
          alt_names: 'Shepherd Cat',
          adaptability: 5,
          affection_level: 5,
          child_friendly: 4,
          dog_friendly: 5,
          energy_level: 3,
          grooming: 2,
          health_issues: 4,
          intelligence: 3,
          shedding_level: 1,
          social_needs: 3,
          stranger_friendly: 3,
          vocalisation: 3,
          experimental: 0,
          hairless: 0,
          natural: 0,
          rare: 0,
          rex: 1,
          suppressed_tail: 0,
          short_legs: 0,
          wikipedia_url: 'https://en.wikipedia.org/wiki/Selkirk_Rex',
          hypoallergenic: 1,
          reference_image_id: 'II9dOZmrw',
        },
      ],
      id: 'II9dOZmrw',
      url: 'https://cdn2.thecatapi.com/images/II9dOZmrw.jpg',
      width: 1920,
      height: 902,
    },
    {
      breeds: [
        {
          weight: {
            imperial: '7 - 20',
            metric: '3 - 9',
          },
          id: 'tvan',
          name: 'Turkish Van',
          cfa_url: 'http://cfa.org/Breeds/BreedsSthruT/TurkishVan.aspx',
          vetstreet_url: 'http://www.vetstreet.com/cats/turkish-van',
          vcahospitals_url:
            'https://vcahospitals.com/know-your-pet/cat-breeds/turkish-van',
          temperament: 'Agile, Intelligent, Loyal, Playful, Energetic',
          origin: 'Turkey',
          country_codes: 'TR',
          country_code: 'TR',
          description:
            'While the Turkish Van loves to jump and climb, play with toys, retrieve and play chase, she is is big and ungainly; this is one cat who doesn’t always land on his feet. While not much of a lap cat, the Van will be happy to cuddle next to you and sleep in your bed. ',
          life_span: '12 - 17',
          indoor: 0,
          alt_names: 'Turkish Cat, Swimming cat',
          adaptability: 5,
          affection_level: 5,
          child_friendly: 4,
          dog_friendly: 5,
          energy_level: 5,
          grooming: 2,
          health_issues: 1,
          intelligence: 5,
          shedding_level: 3,
          social_needs: 4,
          stranger_friendly: 4,
          vocalisation: 5,
          experimental: 0,
          hairless: 0,
          natural: 1,
          rare: 0,
          rex: 0,
          suppressed_tail: 0,
          short_legs: 0,
          wikipedia_url: 'https://en.wikipedia.org/wiki/Turkish_Van',
          hypoallergenic: 0,
          reference_image_id: 'sxIXJax6h',
        },
      ],
      id: 'VXppGG5rK',
      url: 'https://cdn2.thecatapi.com/images/VXppGG5rK.jpg',
      width: 1250,
      height: 650,
    },
  ],
  paginationCount: 955,
};
